import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers'
import Header from '@/components/organisms/Navbar'
import Footer from '@/components/organisms/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <Providers>
          <div className="flex flex-col w-full items-center ">
            <div className="container flex flex-col min-h-screen">
            <Header />
            <main className='grow'> {children}</main>
            <Footer/>
          </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
